import { create } from "zustand";
import {
  get as getFromIndexDB,
  set as setToIndexDB,
  keys,
  del,
} from "idb-keyval";

import { DataSourceType } from "@/types/json";
import { DataFile, DataLoadWithDuckDBResult } from "@/types/multiFile";
import { QueryIntent, IntentResult } from "@/lib/ai/intentClassifier";
import { EnhancedIntentResult } from "@/lib/ai/enhancedIntentClassifier";
import { SQLGenerationResult } from "@/lib/ai/contextAwareSQLGenerator";

/**
 * Interface for a saved or recent query
 */
export interface SavedQuery {
  /** Unique identifier for the query */
  id: string;
  /** User-provided or auto-generated name */
  name: string;
  /** SQL query text */
  query: string;
  /** Timestamp when the query was saved */
  timestamp: number;
  /** Whether this is a favorite/saved query */
  isFavorite: boolean;
}

/**
 * Interface for data insights generated by AI analysis
 */
export interface DataInsight {
  id: string;
  type:
    | "correlation"
    | "outlier"
    | "trend"
    | "distribution"
    | "quality"
    | "performance";
  title: string;
  description: string;
  severity: "info" | "warning" | "critical";
  suggestedAction?: string;
  confidence: number;
  fileId: string;
  tableName: string;
  timestamp: number;
}

/**
 * Interface for chart suggestions generated by AI
 */
export interface ChartSuggestion {
  id: string;
  type: "bar" | "line" | "pie" | "scatter" | "area" | "column";
  title: string;
  description: string;
  confidence: number;
  xAxis: string;
  yAxis: string;
  colorBy?: string;
  reasoning: string;
  fileId: string;
  tableName: string;
  sampleQuery?: string;
  previewData?: any[];
}

/**
 * Interface for SQL query suggestions
 */
export interface SqlSuggestion {
  id: string;
  title: string;
  description: string;
  query: string;
  category:
    | "exploration"
    | "aggregation"
    | "filtering"
    | "joining"
    | "analysis";
  confidence: number;
  fileId: string;
  tableName: string;
}

/**
 * Interface for AI analysis results per file
 */
export interface AIAnalysisResult {
  fileId: string;
  tableName: string;
  insights: DataInsight[];
  chartSuggestions: ChartSuggestion[];
  sqlSuggestions: SqlSuggestion[];
  analysisTimestamp: number;
  dataFingerprint: string; // hash of data structure to detect changes
}

/**
 * Enhanced interface for natural language query processing results
 */
export interface NLQueryResult {
  query: string;
  intent: QueryIntent;
  confidence: number;
  generatedSQL?: string;
  explanation?: string;
  chartSuggestion?: ChartSuggestion;
  error?: string;
  // Enhanced fields from our new system
  approach?: "pattern" | "small_model" | "large_model" | "template";
  usedTables?: string[];
  usedColumns?: string[];
  complexity?: "simple" | "medium" | "complex";
  processingTime?: number;
  warnings?: string[];
  suggestions?: string[];
  canExecute?: boolean;
  intentResult?: EnhancedIntentResult;
  sqlResult?: SQLGenerationResult;
}

/**
 * Interface for conversation context tracking
 */
export interface ConversationContext {
  currentTable?: string;
  recentColumns: string[];
  recentOperations: string[];
  userPreferences: {
    preferredChartTypes: string[];
    defaultLimit: number;
    showConfidenceScores: boolean;
    preferredApproach: "fast" | "accurate" | "auto";
  };
  sessionStartTime: number;
}

/**
 * Interface for model loading and performance state
 */
export interface ModelLoadingState {
  isLoading: boolean;
  loadedModels: string[];
  loadingProgress: Record<string, number>;
  loadingErrors: Record<string, string>;
}

/**
 * Interface for application state managed by Zustand
 */
interface AIAssistantState {
  // Multi-file state
  /** Array of all imported files/datasets */
  files: DataFile[];
  /** ID of the currently active/viewed file */
  activeFileId: string | null;

  // UI state
  /** Currently active tab ID */
  activeTab: string;
  /** View mode for JSON data (table or tree) */
  jsonViewMode: "table" | "tree";
  /** Sidebar collapsed state */
  sidebarCollapsed: boolean;

  // AI Assistant state
  /** Whether the AI panel is expanded */
  isExpanded: boolean;
  /** Current mode: suggestions, chat, or multi-file */
  activeMode: "suggestions" | "chat" | "multi-file";
  /** File IDs selected for analysis */
  activeFileIds: string[];

  // Analysis state
  /** Map of file analysis results */
  analysisResults: Map<string, AIAnalysisResult>;
  /** Whether analysis is currently running */
  isAnalyzing: boolean;
  /** Progress of current analysis (0-1) */
  analysisProgress: number;
  /** Timestamp of last analysis */
  lastAnalysisTime: number;

  // Enhanced Natural Language Processing state
  /** Current NL query being processed */
  currentNLQuery: string;
  /** Results from NL query processing */
  nlQueryResults: NLQueryResult[];
  /** Whether NL processing is active */
  isProcessingNL: boolean;
  /** Enhanced processing statistics */
  processingStats: {
    totalQueries: number;
    successfulQueries: number;
    averageProcessingTime: number;
    complexityDistribution: { simple: number; medium: number; complex: number };
  };

  // Model loading state
  modelLoadingState: ModelLoadingState;

  // Conversation state
  /** Chat message history */
  chatHistory: Array<{
    id: string;
    type: "user" | "assistant" | "system";
    message: string;
    timestamp: number;
    context?: {
      fileId: string;
      query?: string;
      chart?: ChartSuggestion;
      sqlResult?: SQLGenerationResult;
    };
  }>;
  /** Current conversation context */
  conversationContext: ConversationContext;
  /** Current chat input value */
  chatInputValue: string;
  /** Whether to show chat suggestions */
  showChatSuggestions: boolean;

  // Discovery & Onboarding state
  /** Whether user has seen onboarding */
  hasSeenOnboarding: boolean;
  /** Whether to show discovery badge */
  showDiscoveryBadge: boolean;
  /** Current discovery step */
  discoveryStep:
    | "file-loaded"
    | "analysis-ready"
    | "suggestions-available"
    | "completed";

  // Performance optimization
  /** Cache for intent classification results */
  intentCache: Map<string, IntentResult>;
  /** Dynamic suggestions based on current context */
  dynamicSuggestions: string[];

  // Query history state
  /** Array of recent queries */
  recentQueries: SavedQuery[];
  /** Array of saved queries */
  savedQueries: SavedQuery[];

  // Multi-file actions
  /** Add a new file to the collection */
  addFile: (fileData: DataLoadWithDuckDBResult) => string;
  /** Remove a file from the collection */
  removeFile: (fileId: string) => void;
  /** Set the active file */
  setActiveFile: (fileId: string) => void;
  /** Close all files */
  closeAllFiles: () => void;
  /** Close all files except the specified one */
  closeOthersFiles: (keepFileId: string) => void;
  /** Update a file's data */
  updateFile: (fileId: string, updates: Partial<DataFile>) => void;

  // UI actions
  /** Change the active tab */
  setActiveTab: (tab: string) => void;
  /** Change the JSON view mode */
  setJsonViewMode: (mode: "table" | "tree") => void;
  /** Toggle sidebar collapsed state */
  toggleSidebar: () => void;
  /** Set sidebar collapsed state */
  setSidebarCollapsed: (collapsed: boolean) => void;

  // AI Assistant actions
  /** Toggle AI panel expanded state */
  toggleExpanded: () => void;
  /** Set active mode */
  setActiveMode: (mode: "suggestions" | "chat" | "multi-file") => void;
  /** Set files for analysis */
  setActiveFiles: (fileIds: string[]) => void;
  /** Add file to analysis */
  addFileToAnalysis: (fileId: string) => void;
  /** Remove file from analysis */
  removeFileFromAnalysis: (fileId: string) => void;

  // Analysis actions
  /** Analyze active files */
  analyzeActiveFiles: () => Promise<void>;
  /** Get analysis for specific file */
  getAnalysisForFile: (fileId: string) => AIAnalysisResult | null;
  /** Clear analysis results */
  clearAnalysis: (fileId?: string) => void;

  // Enhanced Natural Language Processing actions
  /** Process natural language query with enhanced system */
  processNaturalLanguageQuery: (
    query: string,
    options?: {
      maxRows?: number;
      preferredApproach?: "fast" | "accurate" | "auto";
      includeOptimizations?: boolean;
      executeImmediately?: boolean;
    }
  ) => Promise<NLQueryResult>;
  /** Set chat input value */
  setChatInputValue: (value: string) => void;
  /** Toggle chat suggestions */
  toggleChatSuggestions: (show?: boolean) => void;
  /** Update conversation context */
  updateConversationContext: (updates: Partial<ConversationContext>) => void;
  /** Clear conversation history */
  clearConversationHistory: () => void;

  // Model management actions
  /** Set model loading state */
  setModelLoadingState: (
    modelId: string,
    state: "idle" | "loading" | "loaded" | "error",
    error?: string
  ) => void;
  /** Set model loading progress */
  setModelLoadingProgress: (modelId: string, progress: any) => void;

  // Intent caching
  /** Cache intent result */
  cacheIntentResult: (query: string, result: IntentResult) => void;
  /** Get cached intent */
  getCachedIntent: (query: string) => IntentResult | null;
  /** Generate dynamic suggestions */
  generateDynamicSuggestions: (fileContext: any) => string[];

  // Legacy actions (for backward compatibility)
  /** Set the data grid content (updates active file) */
  setData: (data: string[][] | undefined) => void;
  /** Load data from parsed result (legacy - delegates to addFile) */
  loadData: (result: DataLoadWithDuckDBResult) => void;
  /** Reset state to initial values */
  resetState: () => void;

  // Query history actions
  /** Add a query to recent history */
  addRecentQuery: (query: string) => void;
  /** Save a query to favorites */
  saveQuery: (query: string, name?: string) => void;
  /** Delete a query */
  deleteQuery: (id: string) => void;
  /** Load queries from storage */
  loadQueriesFromStorage: () => void;

  // Discovery & Onboarding actions
  /** Mark onboarding as seen */
  markOnboardingSeen: () => void;
  /** Update discovery step */
  updateDiscoveryStep: (step: AIAssistantState["discoveryStep"]) => void;
  /** Hide discovery badge */
  hideDiscoveryBadge: () => void;

  // Chat actions
  /** Add chat message */
  addChatMessage: (
    message: string,
    type: "user" | "assistant" | "system",
    context?: any
  ) => void;
  /** Clear chat history */
  clearChatHistory: () => void;

  // Persistence
  /** Load from storage */
  loadFromStorage: () => Promise<void>;
  /** Save to storage */
  saveToStorage: () => Promise<void>;
}

// Enhanced initial state
const initialState = {
  // Multi-file state
  files: [],
  activeFileId: null,

  // UI state
  activeTab: "preview",
  jsonViewMode: "table" as const,
  sidebarCollapsed: false,

  // AI Assistant state
  isExpanded: false,
  activeMode: "suggestions" as const,
  activeFileIds: [],

  // Analysis state
  analysisResults: new Map(),
  isAnalyzing: false,
  analysisProgress: 0,
  lastAnalysisTime: 0,

  // Enhanced Natural Language Processing state
  currentNLQuery: "",
  nlQueryResults: [],
  isProcessingNL: false,
  processingStats: {
    totalQueries: 0,
    successfulQueries: 0,
    averageProcessingTime: 0,
    complexityDistribution: { simple: 0, medium: 0, complex: 0 },
  },

  // Model loading state
  modelLoadingState: {
    isLoading: false,
    loadedModels: [],
    loadingProgress: {},
    loadingErrors: {},
  },

  // Conversation state
  chatHistory: [],
  conversationContext: {
    recentColumns: [],
    recentOperations: [],
    userPreferences: {
      preferredChartTypes: ["bar", "line"],
      defaultLimit: 1000,
      showConfidenceScores: true,
      preferredApproach: "auto" as const,
    },
    sessionStartTime: Date.now(),
  },
  chatInputValue: "",
  showChatSuggestions: true,

  // Discovery & Onboarding state
  hasSeenOnboarding: false,
  showDiscoveryBadge: false,
  discoveryStep: "file-loaded" as const,

  // Performance optimization
  intentCache: new Map(),
  dynamicSuggestions: [],

  // Query history state
  recentQueries: [],
  savedQueries: [],
};

/**
 * Maximum number of recent queries to keep
 */
const MAX_RECENT_QUERIES = 50;

/**
 * Generate a unique file ID
 */
const generateFileId = (): string => {
  return `file_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

/**
 * Generate a safe table name from file name
 */
const generateTableName = (fileName: string, fileId: string): string => {
  const safeName = fileName
    .replace(/\.[^/.]+$/, "") // Remove extension
    .replace(/[^a-zA-Z0-9_]/g, "_") // Replace non-alphanumeric with underscore
    .toLowerCase();

  // Add file ID suffix to ensure uniqueness
  const shortId = fileId.split("_").pop() || "unknown";
  return `${safeName}_${shortId}`;
};

/**
 * Generate data fingerprint for change detection
 */
function generateDataFingerprint(data: any[], schema: any[]): string {
  const structure = {
    rowCount: data.length,
    columnCount: schema.length,
    columns: schema.map((col) => ({ name: col.name, type: col.type })),
    sampleData: data.slice(0, 5).map((row) => Object.keys(row).length),
  };
  return btoa(JSON.stringify(structure));
}

// Load sidebar collapsed state from localStorage on initialization
const getSavedSidebarState = () => {
  try {
    const savedState = localStorage.getItem("sidebar-collapsed");
    return savedState === "true"; // Convert string to boolean
  } catch (e) {
    return false; // Default to expanded if there's an error
  }
};

/**
 * Zustand store for managing AI Assistant state
 */
export const useAIAssistantStore = create<AIAssistantState>((set, get) => ({
  ...initialState,
  sidebarCollapsed: getSavedSidebarState(),

  // Multi-file actions (unchanged)
  addFile: (fileData: DataLoadWithDuckDBResult): string => {
    const fileId = generateFileId();
    const tableName =
      fileData.tableName || generateTableName(fileData.fileName, fileId);

    const newFile: DataFile = {
      id: fileId,
      fileName: fileData.fileName,
      data: fileData.data,
      columnTypes: fileData.columnTypes,
      sourceType: fileData.sourceType || DataSourceType.CSV,
      rawData: fileData.rawData || null,
      jsonSchema: fileData.schema || null,
      rowCount: fileData.rowCount,
      columnCount: fileData.columnCount,
      loadedToDuckDB: fileData.loadedToDuckDB,
      tableName: tableName,
      isRemote: fileData.isRemote || false,
      remoteURL: fileData.remoteURL,
      remoteProvider: fileData.remoteProvider,
      googleSheets: fileData.googleSheets,
      importedAt: Date.now(),
      lastAccessedAt: Date.now(),
    };

    set((state) => ({
      files: [...state.files, newFile],
      activeFileId: fileId, // Auto-switch to new file
      activeFileIds: [fileId], // Auto-select for AI analysis
    }));

    // Load queries from storage when first file is added
    if (get().files.length === 1) {
      get().loadQueriesFromStorage();
    }

    return fileId;
  },

  removeFile: (fileId: string) => {
    set((state) => {
      const newFiles = state.files.filter((f) => f.id !== fileId);
      let newActiveFileId = state.activeFileId;

      // If we're removing the active file, switch to another file
      if (state.activeFileId === fileId) {
        if (newFiles.length > 0) {
          // Try to find the next file, or fallback to the first
          const currentIndex = state.files.findIndex((f) => f.id === fileId);
          const nextFile =
            newFiles[Math.min(currentIndex, newFiles.length - 1)];
          newActiveFileId = nextFile.id;
        } else {
          newActiveFileId = null;
        }
      }

      // Remove from active analysis files
      const newActiveFileIds = state.activeFileIds.filter(
        (id) => id !== fileId
      );

      return {
        files: newFiles,
        activeFileId: newActiveFileId,
        activeFileIds: newActiveFileIds,
      };
    });
  },

  setActiveFile: (fileId: string) => {
    set((state) => {
      // Update last accessed time
      const updatedFiles = state.files.map((file) =>
        file.id === fileId ? { ...file, lastAccessedAt: Date.now() } : file
      );

      return {
        files: updatedFiles,
        activeFileId: fileId,
      };
    });
  },

  closeAllFiles: () => {
    set({ files: [], activeFileId: null, activeFileIds: [] });
  },

  closeOthersFiles: (keepFileId: string) => {
    set((state) => ({
      files: state.files.filter((f) => f.id === keepFileId),
      activeFileId: keepFileId,
      activeFileIds: state.activeFileIds.filter((id) => id === keepFileId),
    }));
  },

  updateFile: (fileId: string, updates: Partial<DataFile>) => {
    set((state) => ({
      files: state.files.map((file) =>
        file.id === fileId
          ? { ...file, ...updates, lastAccessedAt: Date.now() }
          : file
      ),
    }));
  },

  // UI actions (unchanged)
  setActiveTab: (activeTab) => set({ activeTab }),
  setJsonViewMode: (jsonViewMode) => set({ jsonViewMode }),
  toggleSidebar: () => {
    const newState = !get().sidebarCollapsed;
    localStorage.setItem("sidebar-collapsed", String(newState));
    set({ sidebarCollapsed: newState });
  },
  setSidebarCollapsed: (collapsed) => {
    localStorage.setItem("sidebar-collapsed", String(collapsed));
    set({ sidebarCollapsed: collapsed });
  },

  // AI Assistant actions (unchanged)
  toggleExpanded: () => {
    const currentState = get();
    const newExpanded = !currentState.isExpanded;
    set({ isExpanded: newExpanded });
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("datakit-ai-expanded", String(newExpanded));
    }
  },
  setActiveMode: (mode) => set({ activeMode: mode }),
  setActiveFiles: (fileIds) => {
    set({ activeFileIds: fileIds });
    if (fileIds.length > 0) {
      setTimeout(() => get().analyzeActiveFiles(), 100);
    }
  },
  addFileToAnalysis: (fileId) => {
    const current = get().activeFileIds;
    if (!current.includes(fileId)) {
      get().setActiveFiles([...current, fileId]);
    }
  },
  removeFileFromAnalysis: (fileId) => {
    const current = get().activeFileIds;
    get().setActiveFiles(current.filter((id) => id !== fileId));
  },

  // Analysis actions (unchanged - keeping existing heuristic analysis)
  analyzeActiveFiles: async () => {
    const state = get();
    if (state.isAnalyzing || state.activeFileIds.length === 0) return;

    set({ isAnalyzing: true, analysisProgress: 0 });

    try {
      const { useAppStore } = await import("@/store/appStore");
      const { useDuckDBStore } = await import("@/store/duckDBStore");

      const appState = useAppStore.getState();
      const duckDBState = useDuckDBStore.getState();
      const newResults = new Map(state.analysisResults);

      for (let i = 0; i < state.activeFileIds.length; i++) {
        const fileId = state.activeFileIds[i];
        const file = appState.files.find((f) => f.id === fileId);
        if (!file) continue;

        set({ analysisProgress: (i / state.activeFileIds.length) * 0.5 });

        const fingerprint = generateDataFingerprint(
          file.data || [],
          file.columnTypes || []
        );
        const existingAnalysis = state.analysisResults.get(fileId);

        if (
          existingAnalysis &&
          existingAnalysis.dataFingerprint === fingerprint
        ) {
          continue;
        }

        const insights = await analyzeDataInsights(file, duckDBState);
        const chartSuggestions = await generateChartSuggestions(
          file,
          duckDBState
        );
        const sqlSuggestions = await generateSqlSuggestions(file, duckDBState);

        set({ analysisProgress: (i + 0.5) / state.activeFileIds.length });

        const result: AIAnalysisResult = {
          fileId,
          tableName: file.tableName,
          insights,
          chartSuggestions,
          sqlSuggestions,
          analysisTimestamp: Date.now(),
          dataFingerprint: fingerprint,
        };

        newResults.set(fileId, result);
        set({ analysisProgress: (i + 1) / state.activeFileIds.length });
      }

      set({
        analysisResults: newResults,
        lastAnalysisTime: Date.now(),
        showDiscoveryBadge: true,
        discoveryStep: "suggestions-available",
      });

      get().saveToStorage();
    } catch (error) {
      console.error("AI Analysis failed:", error);
    } finally {
      set({ isAnalyzing: false, analysisProgress: 0 });
    }
  },

  getAnalysisForFile: (fileId) => {
    return get().analysisResults.get(fileId) || null;
  },

  clearAnalysis: (fileId) => {
    const newResults = new Map(get().analysisResults);
    if (fileId) {
      newResults.delete(fileId);
    } else {
      newResults.clear();
    }
    set({ analysisResults: newResults });
  },

  // ENHANCED Natural Language Processing actions
  processNaturalLanguageQuery: async (query: string, options = {}) => {
    if (!query.trim()) {
      return {
        query,
        intent: "unknown" as QueryIntent,
        confidence: 0,
        error: "Query cannot be empty",
      };
    }

    const startTime = Date.now();
    set({ isProcessingNL: true, currentNLQuery: query });

    try {
      console.log(`[AIAssistantStore] Processing enhanced query: "${query}"`);

      // Import our enhanced system
      const { enhancedIntentClassifier } = await import(
        "@/lib/ai/enhancedIntentClassifier"
      );
      const { contextAwareSQLGenerator } = await import(
        "@/lib/ai/contextAwareSQLGenerator"
      );

      // Step 1: Enhanced Intent Classification
      const intentResult = await enhancedIntentClassifier.classifyWithSchema(
        query,
        {
          useMLModels: true,
          includeSchemaContext: true,
          maxContextTables: 5,
        }
      );

      console.log(
        `[AIAssistantStore] Intent classified: ${intentResult.intent} (${intentResult.confidence})`
      );

      // Update conversation context
      get().updateConversationContext({
        recentColumns: [
          ...new Set([
            ...get().conversationContext.recentColumns,
            ...intentResult.resolvedColumns,
          ]),
        ].slice(-10),
        recentOperations: [
          ...new Set([
            ...get().conversationContext.recentOperations,
            ...intentResult.entities.operations,
          ]),
        ].slice(-10),
      });

      // Step 2: Context-Aware SQL Generation
      let sqlResult: SQLGenerationResult | undefined;
      let generatedSQL: string | undefined;

      if (shouldGenerateSQL(intentResult.intent)) {
        try {
          sqlResult = await contextAwareSQLGenerator.generateSQL({
            intent: intentResult.intent,
            entities: intentResult.entities,
            userQuery: query,
            maxRows: options.maxRows || 100,
            preferredApproach:
              options.preferredApproach ||
              get().conversationContext.userPreferences.preferredApproach,
            includeOptimizations: options.includeOptimizations !== false,
          });

          generatedSQL = sqlResult.sql;
          console.log(
            `[AIAssistantStore] SQL generated using ${sqlResult.approach} approach`
          );
        } catch (sqlError) {
          console.warn("[AIAssistantStore] SQL generation failed:", sqlError);
        }
      }

      const processingTime = Date.now() - startTime;

      // Build comprehensive result
      const result: NLQueryResult = {
        query,
        intent: intentResult.intent,
        confidence: Math.min(
          intentResult.confidence,
          sqlResult?.confidence || 1
        ),
        generatedSQL,
        explanation: sqlResult?.explanation || intentResult.suggestedAction,
        approach: sqlResult?.approach || "pattern",
        usedTables: sqlResult?.usedTables || [],
        usedColumns: sqlResult?.usedColumns || intentResult.resolvedColumns,
        complexity: sqlResult?.estimatedComplexity || intentResult.complexity,
        processingTime,
        warnings: [
          ...(intentResult.warnings || []),
          ...(sqlResult?.warnings || []),
        ],
        suggestions: [
          ...(intentResult.suggestions || []),
          ...(sqlResult?.suggestions || []),
        ],
        canExecute: !!generatedSQL && (sqlResult?.confidence || 0) > 0.5,
        intentResult,
        sqlResult,
      };

      // Generate chart suggestion if appropriate
      if (intentResult.intent === "create_chart") {
        result.chartSuggestion = generateChartSuggestionFromIntent(
          intentResult,
          intentResult.resolvedColumns
        );
      }

      // Update processing statistics
      updateProcessingStats(result);

      set((state) => ({
        nlQueryResults: [...state.nlQueryResults, result],
        isProcessingNL: false,
        currentNLQuery: "",
      }));

      console.log(
        `[AIAssistantStore] Processing completed in ${processingTime}ms`
      );
      return result;
    } catch (error) {
      console.error("Enhanced natural language processing failed:", error);

      const errorResult: NLQueryResult = {
        query,
        intent: "unknown" as QueryIntent,
        confidence: 0,
        error:
          error instanceof Error ? error.message : "Failed to process query",
        processingTime: Date.now() - startTime,
        canExecute: false,
      };

      set({ isProcessingNL: false, currentNLQuery: "" });
      return errorResult;
    }
  },

  // Model management actions
  setModelLoadingState: (
    modelId: string,
    state: "idle" | "loading" | "loaded" | "error",
    error?: string
  ) => {
    set((currentState) => ({
      modelLoadingState: {
        ...currentState.modelLoadingState,
        isLoading: state === "loading",
        loadedModels:
          state === "loaded"
            ? [
                ...currentState.modelLoadingState.loadedModels.filter(
                  (id) => id !== modelId
                ),
                modelId,
              ]
            : currentState.modelLoadingState.loadedModels.filter(
                (id) => id !== modelId
              ),
        loadingErrors: error
          ? {
              ...currentState.modelLoadingState.loadingErrors,
              [modelId]: error,
            }
          : {
              ...currentState.modelLoadingState.loadingErrors,
              [modelId]: undefined,
            },
      },
    }));
  },

  setModelLoadingProgress: (modelId: string, progress: any) => {
    set((currentState) => ({
      modelLoadingState: {
        ...currentState.modelLoadingState,
        loadingProgress: {
          ...currentState.modelLoadingState.loadingProgress,
          [modelId]: progress,
        },
      },
    }));
  },

  setChatInputValue: (value) => set({ chatInputValue: value }),

  toggleChatSuggestions: (show) =>
    set((state) => ({
      showChatSuggestions:
        show !== undefined ? show : !state.showChatSuggestions,
    })),

  updateConversationContext: (updates) =>
    set((state) => ({
      conversationContext: { ...state.conversationContext, ...updates },
    })),

  clearConversationHistory: () =>
    set({
      chatHistory: [],
      nlQueryResults: [],
      conversationContext: {
        ...get().conversationContext,
        recentColumns: [],
        recentOperations: [],
        sessionStartTime: Date.now(),
      },
    }),

  cacheIntentResult: (query, result) => {
    const cache = new Map(get().intentCache);
    cache.set(query.toLowerCase().trim(), result);
    if (cache.size > 50) {
      const firstKey = cache.keys().next().value;
      cache.delete(firstKey);
    }
    set({ intentCache: cache });
  },

  getCachedIntent: (query) => {
    return get().intentCache.get(query.toLowerCase().trim()) || null;
  },

  generateDynamicSuggestions: (fileContext) => {
    if (!fileContext || !fileContext.columnTypes) {
      return [];
    }

    const columns = fileContext.columnTypes
      .map((col: any, index: number) => {
        if (col && typeof col === "object" && col.name) {
          return col.name;
        }
        if (fileContext.data?.length > 0) {
          return Object.keys(fileContext.data[0])[index];
        }
        return null;
      })
      .filter(Boolean);

    const suggestions = [
      `Show me the data`,
      `Create a chart with ${columns[0]} and ${columns[1] || columns[0]}`,
      `What patterns do you see?`,
      `Find correlations`,
      `Summarize this dataset`,
    ];

    if (columns.length > 0) {
      suggestions.push(`Filter by ${columns[0]}`);
      suggestions.push(`Sort by ${columns[0]}`);
    }

    const dateColumns = columns.filter(
      (col) =>
        col.toLowerCase().includes("date") || col.toLowerCase().includes("time")
    );

    if (dateColumns.length > 0) {
      suggestions.push(`Show trends over ${dateColumns[0]}`);
      suggestions.push(`Analyze ${dateColumns[0]} patterns`);
    }

    set({ dynamicSuggestions: suggestions.slice(0, 6) });
    return suggestions;
  },

  // Legacy actions
  setData: (data) => {
    // For backward compatibility, update active file if exists
    const state = get();
    const activeFile = state.files.find((f) => f.id === state.activeFileId);
    if (activeFile && data) {
      get().updateFile(activeFile.id, { data });
    }
  },

  // Load data from result (legacy - now delegates to addFile)
  loadData: (result: DataLoadWithDuckDBResult) => {
    get().addFile(result);
  },

  // Reset state
  resetState: () =>
    set({
      ...initialState,
      sidebarCollapsed: get().sidebarCollapsed,
    }),

  // Query history actions
  addRecentQuery: (query) => {
    if (!query.trim()) return;

    const id = `recent-query:${Date.now()}`;
    const recentQuery: SavedQuery = {
      id,
      name: `Query at ${new Date().toLocaleString()}`,
      query,
      timestamp: Date.now(),
      isFavorite: false,
    };

    setToIndexDB(id, recentQuery).catch(console.error);

    set((state) => ({
      recentQueries: [
        recentQuery,
        ...state.recentQueries
          .filter((q) => q.query !== query)
          .slice(0, MAX_RECENT_QUERIES - 1),
      ],
    }));
  },

  loadQueriesFromStorage: async () => {
    try {
      const allKeys = await keys();
      const savedKeys = allKeys.filter((k) =>
        String(k).startsWith("saved-query:")
      );
      const recentKeys = allKeys.filter((k) =>
        String(k).startsWith("recent-query:")
      );

      const savedQueryPromises = savedKeys.map((key) => getFromIndexDB(key));
      const savedQueries = await Promise.all(savedQueryPromises);

      const recentQueryPromises = recentKeys.map((key) => getFromIndexDB(key));
      const recentQueries = await Promise.all(recentQueryPromises);

      set({
        savedQueries: savedQueries.sort((a, b) => b.timestamp - a.timestamp),
        recentQueries: recentQueries.sort((a, b) => b.timestamp - a.timestamp),
      });
    } catch (err) {
      console.error("Error loading queries from storage:", err);
    }
  },

  saveQuery: (query, name) => {
    if (!query.trim()) return;

    const id = `saved-query:${Date.now()}`;
    const savedQuery: SavedQuery = {
      id,
      name: name || `Saved Query ${new Date().toLocaleString()}`,
      query,
      timestamp: Date.now(),
      isFavorite: true,
    };

    setToIndexDB(id, savedQuery).catch(console.error);

    set((state) => ({
      savedQueries: [savedQuery, ...state.savedQueries],
    }));
  },

  deleteQuery: (id) => {
    del(id).catch(console.error);

    if (id.startsWith("saved-query:")) {
      set((state) => ({
        savedQueries: state.savedQueries.filter((q) => q.id !== id),
      }));
    } else {
      set((state) => ({
        recentQueries: state.recentQueries.filter((q) => q.id !== id),
      }));
    }
  },

  // Discovery & Onboarding actions
  markOnboardingSeen: () => {
    set({ hasSeenOnboarding: true });
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("datakit-ai-onboarding-seen", "true");
    }
  },

  updateDiscoveryStep: (step) => set({ discoveryStep: step }),

  hideDiscoveryBadge: () => set({ showDiscoveryBadge: false }),

  // Chat actions
  addChatMessage: (message, type, context) => {
    const chatMessage = {
      id: `msg-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      type,
      message,
      timestamp: Date.now(),
      context,
    };

    set((state) => ({
      chatHistory: [...state.chatHistory, chatMessage],
    }));
  },

  clearChatHistory: () => set({ chatHistory: [] }),

  // Persistence
  loadFromStorage: async () => {
    try {
      // Load UI preferences
      if (typeof localStorage !== "undefined") {
        const expandedState = localStorage.getItem("datakit-ai-expanded");
        const onboardingSeen = localStorage.getItem(
          "datakit-ai-onboarding-seen"
        );

        set({
          isExpanded: expandedState === "true",
          hasSeenOnboarding: onboardingSeen === "true",
        });
      }

      // Load chat history from IndexedDB
      const chatHistory = (await getFromIndexDB("ai-chat-history")) || [];
      set({ chatHistory });
    } catch (error) {
      console.error("Failed to load AI assistant data from storage:", error);
    }
  },

  saveToStorage: async () => {
    try {
      // Save chat history to IndexedDB
      await setToIndexDB("ai-chat-history", get().chatHistory);
    } catch (error) {
      console.error("Failed to save AI assistant data to storage:", error);
    }
  },
}));

// Helper functions for analysis

async function analyzeDataInsights(
  file: any,
  duckDBState: any
): Promise<DataInsight[]> {
  const insights: DataInsight[] = [];

  if (!file.data || !file.columnTypes) return insights;

  const data = file.data;
  const schema = file.columnTypes;
  const tableName = file.tableName;

  // Handle different schema formats safely
  const getColumnInfo = (col: any, index: number) => {
    if (col && typeof col === "object" && col.name) {
      return { name: col.name, type: col.type };
    }

    if (data.length > 0) {
      const dataKeys = Object.keys(data[0]);
      const name = dataKeys[index];
      return { name, type: col };
    }

    return null;
  };

  const columnInfo = schema
    .map((col: any, index: number) => getColumnInfo(col, index))
    .filter(Boolean);

  if (columnInfo.length === 0) return insights;

  // Data Quality Analysis
  const nullCounts = columnInfo
    .map((col) => {
      const nullCount = data.filter(
        (row) => row[col.name] == null || row[col.name] === ""
      ).length;
      return {
        column: col.name,
        nulls: nullCount,
        percentage: (nullCount / data.length) * 100,
      };
    })
    .filter((item) => item.percentage > 5);

  if (nullCounts.length > 0) {
    insights.push({
      id: `quality-missing-${file.id}`,
      type: "quality",
      title: "Missing Data Detected",
      description: `${
        nullCounts.length
      } columns have >5% missing values: ${nullCounts
        .map((c) => c.column)
        .join(", ")}`,
      severity: nullCounts.some((c) => c.percentage > 25) ? "warning" : "info",
      suggestedAction: "Consider data cleaning or filtering before analysis",
      confidence: 0.9,
      fileId: file.id,
      tableName,
      timestamp: Date.now(),
    });
  }

  // Dataset Size Analysis
  if (data.length > 50000) {
    insights.push({
      id: `performance-large-${file.id}`,
      type: "performance",
      title: "Large Dataset",
      description: `${data.length.toLocaleString()} rows detected - consider sampling for visualization`,
      severity: "info",
      suggestedAction: "Use LIMIT clause or sampling for better performance",
      confidence: 0.8,
      fileId: file.id,
      tableName,
      timestamp: Date.now(),
    });
  }

  // Duplicate Detection (sample-based for performance)
  const sampleSize = Math.min(1000, data.length);
  const sample = data.slice(0, sampleSize);
  const uniqueRows = new Set(sample.map((row) => JSON.stringify(row))).size;
  const duplicatePercentage = ((sampleSize - uniqueRows) / sampleSize) * 100;

  if (duplicatePercentage > 10) {
    insights.push({
      id: `quality-duplicates-${file.id}`,
      type: "quality",
      title: "Potential Duplicates",
      description: `~${Math.round(
        duplicatePercentage
      )}% duplicate rows detected in sample`,
      severity: duplicatePercentage > 25 ? "warning" : "info",
      suggestedAction: "Consider deduplication before analysis",
      confidence: 0.7,
      fileId: file.id,
      tableName,
      timestamp: Date.now(),
    });
  }

  return insights;
}

async function generateChartSuggestions(
  file: any,
  duckDBState: any
): Promise<ChartSuggestion[]> {
  const suggestions: ChartSuggestion[] = [];

  if (!file.data || !file.columnTypes) return suggestions;

  const data = file.data;
  const schema = file.columnTypes;
  const tableName = file.tableName;

  // Handle different schema formats safely
  const getColumnInfo = (col: any, index: number) => {
    if (col && typeof col === "object" && col.name) {
      return { name: col.name, type: col.type };
    }

    if (data.length > 0) {
      const dataKeys = Object.keys(data[0]);
      const name = dataKeys[index];
      return { name, type: col };
    }

    return null;
  };

  const columnInfo = schema
    .map((col: any, index: number) => getColumnInfo(col, index))
    .filter(Boolean);

  if (columnInfo.length === 0) return suggestions;

  // Get column types - handle both string types and ColumnType enums
  const numericColumns = columnInfo
    .filter(
      (col) => col.type === "number" || col.type === "Number" || col.type === 1 // ColumnType.Number = 1
    )
    .map((col) => col.name);

  const categoricalColumns = columnInfo
    .filter(
      (col) => col.type === "string" || col.type === "String" || col.type === 0 // ColumnType.String = 0
    )
    .map((col) => col.name);

  const dateColumns = columnInfo
    .filter((col) => {
      const name = col.name ? col.name.toLowerCase() : "";
      return (
        name.includes("date") ||
        name.includes("time") ||
        col.type === "date" ||
        col.type === "Date" ||
        col.type === 2
      ); // ColumnType.Date = 2
    })
    .map((col) => col.name);

  // Time Series Detection
  if (dateColumns.length > 0 && numericColumns.length > 0) {
    suggestions.push({
      id: `time-series-${file.id}`,
      type: "line",
      title: "Time Series Trend",
      description: `Track ${numericColumns[0]} over time`,
      confidence: 0.9,
      xAxis: dateColumns[0],
      yAxis: numericColumns[0],
      reasoning:
        "Date column detected with numeric data - perfect for trend analysis",
      fileId: file.id,
      tableName,
      sampleQuery: `SELECT "${dateColumns[0]}", "${numericColumns[0]}" FROM "${tableName}" ORDER BY "${dateColumns[0]}" LIMIT 100`,
    });
  }

  // Category Distribution
  if (categoricalColumns.length > 0 && numericColumns.length > 0) {
    // Check cardinality of categorical column
    const sampleData = data.slice(0, 1000);
    const uniqueValues = new Set(
      sampleData.map((row) => row[categoricalColumns[0]])
    ).size;

    if (uniqueValues <= 20) {
      // Good for bar chart
      suggestions.push({
        id: `category-bar-${file.id}`,
        type: "bar",
        title: "Category Comparison",
        description: `Compare ${numericColumns[0]} across ${categoricalColumns[0]}`,
        confidence: 0.85,
        xAxis: categoricalColumns[0],
        yAxis: numericColumns[0],
        reasoning: `Found ${uniqueValues} categories - ideal for comparison`,
        fileId: file.id,
        tableName,
        sampleQuery: `SELECT "${categoricalColumns[0]}", AVG("${numericColumns[0]}") as avg_value FROM "${tableName}" GROUP BY "${categoricalColumns[0]}" LIMIT 20`,
      });
    }

    if (uniqueValues <= 8) {
      // Good for pie chart
      suggestions.push({
        id: `category-pie-${file.id}`,
        type: "pie",
        title: "Distribution Breakdown",
        description: `Show distribution of ${categoricalColumns[0]}`,
        confidence: 0.8,
        xAxis: categoricalColumns[0],
        yAxis: "count",
        reasoning: `${uniqueValues} categories perfect for pie chart`,
        fileId: file.id,
        tableName,
        sampleQuery: `SELECT "${categoricalColumns[0]}", COUNT(*) as count FROM "${tableName}" GROUP BY "${categoricalColumns[0]}"`,
      });
    }
  }

  // Correlation Analysis
  if (numericColumns.length >= 2) {
    suggestions.push({
      id: `correlation-scatter-${file.id}`,
      type: "scatter",
      title: "Correlation Analysis",
      description: `Explore relationship between ${numericColumns[0]} and ${numericColumns[1]}`,
      confidence: 0.75,
      xAxis: numericColumns[0],
      yAxis: numericColumns[1],
      colorBy:
        categoricalColumns.length > 0 ? categoricalColumns[0] : undefined,
      reasoning: "Multiple numeric columns - good for correlation analysis",
      fileId: file.id,
      tableName,
      sampleQuery: `SELECT "${numericColumns[0]}", "${numericColumns[1]}"${
        categoricalColumns.length > 0 ? `, "${categoricalColumns[0]}"` : ""
      } FROM "${tableName}" LIMIT 500`,
    });
  }

  return suggestions;
}

async function generateSqlSuggestions(
  file: any,
  duckDBState: any
): Promise<SqlSuggestion[]> {
  const suggestions: SqlSuggestion[] = [];

  if (!file.data || !file.columnTypes) return suggestions;

  const schema = file.columnTypes;
  const tableName = file.tableName;

  // Handle different schema formats safely
  const getColumnInfo = (col: any, index: number) => {
    if (col && typeof col === "object" && col.name) {
      return { name: col.name, type: col.type };
    }

    if (file.data.length > 0) {
      const dataKeys = Object.keys(file.data[0]);
      const name = dataKeys[index];
      return { name, type: col };
    }

    return null;
  };

  const columnInfo = schema
    .map((col: any, index: number) => getColumnInfo(col, index))
    .filter(Boolean);

  if (columnInfo.length === 0) return suggestions;

  const numericColumns = columnInfo
    .filter(
      (col) => col.type === "number" || col.type === "Number" || col.type === 1
    )
    .map((col) => col.name);

  const categoricalColumns = columnInfo
    .filter(
      (col) => col.type === "string" || col.type === "String" || col.type === 0
    )
    .map((col) => col.name);

  // Basic exploration queries
  suggestions.push({
    id: `explore-overview-${file.id}`,
    title: "Data Overview",
    description: "Get basic statistics and structure",
    query: `SELECT COUNT(*) as total_rows, COUNT(DISTINCT *) as unique_rows FROM "${tableName}"`,
    category: "exploration",
    confidence: 0.9,
    fileId: file.id,
    tableName,
  });

  // Top/Bottom records
  if (numericColumns.length > 0) {
    suggestions.push({
      id: `explore-top-${file.id}`,
      title: `Top Records by ${numericColumns[0]}`,
      description: `Find highest values in ${numericColumns[0]}`,
      query: `SELECT * FROM "${tableName}" ORDER BY "${numericColumns[0]}" DESC LIMIT 10`,
      category: "exploration",
      confidence: 0.8,
      fileId: file.id,
      tableName,
    });
  }

  // Group by analysis
  if (categoricalColumns.length > 0 && numericColumns.length > 0) {
    suggestions.push({
      id: `analyze-groups-${file.id}`,
      title: `Analysis by ${categoricalColumns[0]}`,
      description: `Aggregate statistics grouped by ${categoricalColumns[0]}`,
      query: `SELECT "${categoricalColumns[0]}", COUNT(*) as count, AVG("${numericColumns[0]}") as avg_${numericColumns[0]} FROM "${tableName}" GROUP BY "${categoricalColumns[0]}" ORDER BY count DESC`,
      category: "aggregation",
      confidence: 0.85,
      fileId: file.id,
      tableName,
    });
  }

  return suggestions;
}

// Helper functions for NL processing

async function generateBasicSQL(
  intentResult: IntentResult,
  fileContext: any
): Promise<string> {
  if (!fileContext?.tableName) {
    throw new Error("No table context available");
  }

  const { intent, entities, parameters } = intentResult;
  const tableName = `"${fileContext.tableName}"`;

  switch (intent) {
    case "show_data":
      const columns =
        entities.columns.length > 0
          ? entities.columns.map((col) => `"${col}"`).join(", ")
          : "*";
      return `SELECT ${columns} FROM ${tableName} LIMIT 100`;

    case "filter_data":
      const filterCol = parameters.filterColumn
        ? `"${parameters.filterColumn}"`
        : '"*"';
      const filterVal = parameters.filterValue || "value";
      return `SELECT * FROM ${tableName} WHERE ${filterCol} = '${filterVal}' LIMIT 100`;

    case "aggregate_data":
      const aggCol = parameters.groupBy
        ? `"${parameters.groupBy}"`
        : entities.columns[0]
        ? `"${entities.columns[0]}"`
        : "column1";
      const agg = parameters.aggregation || "COUNT";
      return `SELECT ${aggCol}, ${agg}(*) as ${agg.toLowerCase()}_value FROM ${tableName} GROUP BY ${aggCol} LIMIT 50`;

    case "sort_data":
      const sortCol = entities.columns[0]
        ? `"${entities.columns[0]}"`
        : "column1";
      return `SELECT * FROM ${tableName} ORDER BY ${sortCol} DESC LIMIT 100`;

    default:
      return `SELECT * FROM ${tableName} LIMIT 10`;
  }
}

function generateChartSuggestionFromIntent(
  intentResult: IntentResult,
  availableColumns: string[]
): ChartSuggestion {
  const { entities, parameters } = intentResult;

  return {
    id: `intent-chart-${Date.now()}`,
    type: parameters.chartType || "bar",
    title: `Chart from: ${intentResult.query}`,
    description: `Visualize ${entities.columns.join(" and ")}`,
    confidence: intentResult.confidence,
    xAxis: parameters.xAxis || availableColumns[0] || "x",
    yAxis:
      parameters.yAxis || availableColumns[1] || availableColumns[0] || "y",
    reasoning: `Generated from natural language: "${intentResult.query}"`,
    fileId: "current",
    tableName: "current_table",
  };
}
